Feat/add user page
lucasmedeiros/game-slot pull request #66
Opened 2021-08-14 02:19 UTC by douglaslimaxx

2021-08-18 02:35 UTC, RaylaMedeiros commented on game-slot/frontend/src/hooks/useGameDetails.ts
> +        if (response.status === 404) setError("Couldn't find the game :(")
acho que seria bom a gente ver direitinho as configurações do eslint pra padronizar essas coisas

2021-08-18 02:42 UTC, RaylaMedeiros requested changes

2021-08-18 02:42 UTC, RaylaMedeiros commented on game-slot/frontend/src/pages/UserList/index.ts
> +export { default as UserList } from './UserList'
por que não colocar o código do UserList logo aqui?

2021-08-18 02:42 UTC, RaylaMedeiros commented on game-slot/frontend/src/pages/UserPage/index.ts
> +export { default as UserPage } from './UserPage'
mesma coisa aqui

2021-08-18 02:42 UTC, RaylaMedeiros commented on game-slot/frontend/src/pages/UserReviews/index.ts
> +export { default as UserReviews } from './UserReviews'
mesma coisa aqui

2021-08-18 14:28 UTC, lucasmedeiros approved these changes

2021-09-04 23:52 UTC, RaylaMedeiros approved these changes

2021-09-06 14:06 UTC, merged